# Netlify configuration file

# The following redirect rule tells Netlify to redirect all paths to index.html.
# This allows React Router to handle the routing client-side.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache settings for images
[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers for all pages
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Build settings
[build]
  publish = "dist"
  command = "npm run build"

# Environment variables
[build.environment]
  NODE_VERSION = "20.11.1"